name: admin
description: The Beeper landing page and console

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  intl: ^0.16.1
  rxdart: ^0.24.1
  websocket: ^0.0.5

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
